-- Step 28: Server-only auto-collection enrollment, device credentials, and batches.
-- Run after step_22_ingest_devices.sql.
--
-- This migration is additive and transaction-wrapped so an error does not leave a
-- partially upgraded schema. CREATE OR REPLACE FUNCTION intentionally replaces
-- the two RPC bodies on rerun while preserving their identities. PostgreSQL also
-- preserves existing function grants on replacement, so the explicit REVOKE and
-- service_role-only GRANT statements below must remain immediately after the RPCs.
-- A future signature or return-type change requires a separately reviewed DROP.
--
-- Hashes and HMACs are generated by the Node API. SQL stores only supplied digest
-- text; enrollment codes and device credentials are never stored in raw form.

begin;

-- The legacy watcher required raw identifiers. New pairing writes only hashes,
-- while existing rows and the legacy unique product_key constraint are preserved.
alter table public.ingest_devices
  alter column product_key drop not null;

alter table public.ingest_devices
  alter column machine_id drop not null;

alter table public.ingest_devices
  add column if not exists machine_id_hash text,
  add column if not exists credential_hash text,
  add column if not exists credential_prefix text,
  add column if not exists status text not null default 'active',
  add column if not exists schedule_time time without time zone not null default '06:00:00',
  add column if not exists schedule_timezone text not null default 'America/New_York',
  add column if not exists agent_version text,
  add column if not exists addon_version text,
  add column if not exists ninjatrader_version text,
  add column if not exists last_seen_at timestamptz,
  add column if not exists last_capture_at timestamptz,
  add column if not exists last_success_at timestamptz,
  add column if not exists last_error_code text,
  add column if not exists last_error_at timestamptz,
  add column if not exists revoked_at timestamptz,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $constraints$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.ingest_devices'::regclass
      and conname = 'ingest_devices_status_check'
  ) then
    alter table public.ingest_devices
      add constraint ingest_devices_status_check
      check (status in ('active', 'revoked'));
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.ingest_devices'::regclass
      and conname = 'ingest_devices_schedule_timezone_check'
  ) then
    alter table public.ingest_devices
      add constraint ingest_devices_schedule_timezone_check
      check (schedule_timezone = 'America/New_York');
  end if;
end
$constraints$;

create unique index if not exists idx_ingest_devices_machine_id_hash_unique
  on public.ingest_devices(machine_id_hash)
  where machine_id_hash is not null;

create unique index if not exists idx_ingest_devices_credential_hash_unique
  on public.ingest_devices(credential_hash)
  where credential_hash is not null;

create table if not exists public.ingest_enrollments (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete cascade,
  code_hash text not null unique check (code_hash <> ''),
  created_by uuid references public.app_users(id) on delete set null,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  consumed_by_device_id uuid references public.ingest_devices(id) on delete set null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  constraint ingest_enrollments_expiry_check check (expires_at > created_at)
);

create index if not exists idx_ingest_enrollments_client_created_at
  on public.ingest_enrollments(client_id, created_at desc);

create index if not exists idx_ingest_enrollments_open_expiry
  on public.ingest_enrollments(expires_at)
  where consumed_at is null and revoked_at is null;

-- CHECK constraints cannot contain a subquery. This immutable helper validates
-- every dynamic row-count value while keeping the batch constraint declarative.
create or replace function public.ingest_row_counts_are_nonnegative(p_row_counts jsonb)
returns boolean
language sql
immutable
strict
set search_path = pg_catalog
as $function$
  select
    jsonb_typeof(p_row_counts) = 'object'
    and not exists (
      select 1
      from jsonb_each(p_row_counts) as entry
      where case
        when jsonb_typeof(entry.value) = 'number' then
          (entry.value #>> '{}')::numeric < 0
          or trunc((entry.value #>> '{}')::numeric) <> (entry.value #>> '{}')::numeric
        else true
      end
    );
$function$;

revoke all on function public.ingest_row_counts_are_nonnegative(jsonb)
  from public, anon, authenticated;
grant execute on function public.ingest_row_counts_are_nonnegative(jsonb)
  to service_role;

create table if not exists public.ingest_batches (
  id uuid primary key default gen_random_uuid(),
  capture_id uuid not null,
  device_id uuid not null references public.ingest_devices(id) on delete restrict,
  client_id uuid not null references public.clients(id) on delete restrict,
  trading_date date not null,
  captured_at timestamptz not null,
  received_at timestamptz not null default now(),
  status text not null default 'received',
  schema_version integer not null,
  storage_path text not null unique,
  content_sha256 text not null,
  byte_count bigint not null,
  row_counts jsonb not null default '{}'::jsonb,
  completeness jsonb not null default '{}'::jsonb,
  daily_import_id uuid references public.daily_imports(id) on delete set null,
  replaces_batch_id uuid references public.ingest_batches(id) on delete set null,
  error_code text,
  error_detail text,
  processed_at timestamptz,
  constraint ingest_batches_device_capture_unique unique (device_id, capture_id),
  constraint ingest_batches_status_check
    check (status in ('received', 'processing', 'processed', 'failed', 'replaced')),
  constraint ingest_batches_schema_version_check check (schema_version > 0),
  constraint ingest_batches_storage_path_check check (storage_path <> ''),
  constraint ingest_batches_content_sha256_check check (content_sha256 <> ''),
  constraint ingest_batches_byte_count_check check (byte_count >= 0),
  constraint ingest_batches_row_counts_check
    check (public.ingest_row_counts_are_nonnegative(row_counts))
);

create index if not exists idx_ingest_batches_client_trading_date
  on public.ingest_batches(client_id, trading_date desc);

create index if not exists idx_ingest_batches_device_received_at
  on public.ingest_batches(device_id, received_at desc);

create index if not exists idx_ingest_batches_status_received_at
  on public.ingest_batches(status, received_at);

create or replace function public.prevent_ingest_batch_storage_path_change()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
begin
  if new.storage_path is distinct from old.storage_path then
    raise exception 'ingest batch storage_path is immutable'
      using errcode = '22023';
  end if;
  return new;
end;
$function$;

revoke all on function public.prevent_ingest_batch_storage_path_change()
  from public, anon, authenticated;
grant execute on function public.prevent_ingest_batch_storage_path_change()
  to service_role;

do $trigger$
begin
  if not exists (
    select 1
    from pg_catalog.pg_trigger
    where tgrelid = 'public.ingest_batches'::regclass
      and tgname = 'ingest_batches_storage_path_immutable'
      and not tgisinternal
  ) then
    create trigger ingest_batches_storage_path_immutable
      before update of storage_path on public.ingest_batches
      for each row
      execute function public.prevent_ingest_batch_storage_path_change();
  end if;
end
$trigger$;

-- Private raw-object bucket. The restrictive policy below is ANDed with any
-- permissive policy applicable to anon/authenticated, so even a broad existing
-- Storage policy cannot authorize this bucket. It remains true for other buckets
-- and does not apply to service_role, which retains its normal RLS bypass.
insert into storage.buckets (id, name, public)
values ('ninjatrader-imports', 'ninjatrader-imports', false)
on conflict (id) do update
set name = excluded.name,
    public = false;

do $storage_policy$
begin
  if not exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'ninjatrader-imports deny browser direct access'
  ) then
    create policy "ninjatrader-imports deny browser direct access"
      on storage.objects
      as restrictive
      for all
      to anon, authenticated
      using (bucket_id <> 'ninjatrader-imports')
      with check (bucket_id <> 'ninjatrader-imports');
  end if;
end
$storage_policy$;

alter table public.ingest_enrollments enable row level security;
alter table public.ingest_devices enable row level security;
alter table public.ingest_batches enable row level security;

revoke all on table public.ingest_enrollments from public, anon, authenticated;
revoke all on table public.ingest_devices from public, anon, authenticated;
revoke all on table public.ingest_batches from public, anon, authenticated;

grant select, insert, update, delete on table public.ingest_enrollments to service_role;
grant select, insert, update, delete on table public.ingest_devices to service_role;
grant select, insert, update, delete on table public.ingest_batches to service_role;

-- Restrictive deny policies make the browser boundary explicit even if table
-- privileges are accidentally granted to anon/authenticated later.
do $policies$
begin
  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'ingest_enrollments'
      and policyname = 'ingest_enrollments deny browser direct access'
  ) then
    create policy "ingest_enrollments deny browser direct access"
      on public.ingest_enrollments
      as restrictive
      for all
      to anon, authenticated
      using (false)
      with check (false);
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'ingest_devices'
      and policyname = 'ingest_devices deny browser direct access'
  ) then
    create policy "ingest_devices deny browser direct access"
      on public.ingest_devices
      as restrictive
      for all
      to anon, authenticated
      using (false)
      with check (false);
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'ingest_batches'
      and policyname = 'ingest_batches deny browser direct access'
  ) then
    create policy "ingest_batches deny browser direct access"
      on public.ingest_batches
      as restrictive
      for all
      to anon, authenticated
      using (false)
      with check (false);
  end if;
end
$policies$;

-- Atomically consume a one-time enrollment. The enrollment row lock serializes
-- concurrent calls. A retry with the winning machine and credential hashes gets
-- the same device; different hashes cannot reuse the consumed code.
create or replace function public.pair_ingest_device(
  p_code_hash text,
  p_machine_hash text,
  p_credential_hash text,
  p_credential_prefix text,
  p_agent_version text,
  p_addon_version text
)
returns public.ingest_devices
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_enrollment public.ingest_enrollments;
  v_device public.ingest_devices;
begin
  if nullif(btrim(p_code_hash), '') is null
    or nullif(btrim(p_machine_hash), '') is null
    or nullif(btrim(p_credential_hash), '') is null
    or nullif(btrim(p_credential_prefix), '') is null then
    raise exception 'pairing digests and credential prefix are required'
      using errcode = '22023';
  end if;

  select enrollment.*
  into v_enrollment
  from public.ingest_enrollments as enrollment
  where enrollment.code_hash = p_code_hash
  for update;

  if not found then
    raise exception 'enrollment code is invalid'
      using errcode = 'P0002';
  end if;

  if v_enrollment.revoked_at is not null then
    raise exception 'enrollment code is revoked'
      using errcode = '22023';
  end if;

  if v_enrollment.consumed_by_device_id is not null then
    select device.*
    into v_device
    from public.ingest_devices as device
    where device.id = v_enrollment.consumed_by_device_id
    for update;

    if not found
      or v_device.machine_id_hash is distinct from p_machine_hash
      or v_device.credential_hash is distinct from p_credential_hash then
      raise exception 'enrollment code was already consumed'
        using errcode = '22023';
    end if;

    if v_device.status <> 'active' or v_device.revoked_at is not null then
      raise exception 'paired device is revoked'
        using errcode = '22023';
    end if;

    return v_device;
  end if;

  if v_enrollment.consumed_at is not null then
    raise exception 'enrollment code has an invalid consumed state'
      using errcode = '22023';
  end if;

  if v_enrollment.expires_at <= clock_timestamp() then
    raise exception 'enrollment code is expired'
      using errcode = '22023';
  end if;

  insert into public.ingest_devices (
    client_id,
    machine_id_hash,
    credential_hash,
    credential_prefix,
    status,
    agent_version,
    addon_version,
    last_seen_at
  )
  values (
    v_enrollment.client_id,
    p_machine_hash,
    p_credential_hash,
    p_credential_prefix,
    'active',
    p_agent_version,
    p_addon_version,
    clock_timestamp()
  )
  returning * into v_device;

  update public.ingest_enrollments
  set consumed_at = clock_timestamp(),
      consumed_by_device_id = v_device.id
  where id = v_enrollment.id;

  return v_device;
end;
$function$;

revoke all on function public.pair_ingest_device(text, text, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.pair_ingest_device(text, text, text, text, text, text)
  to service_role;

-- Serializing on the device closes the "no row exists yet" race. Once a claim
-- wins, same-payload retries return that row; a reused capture ID or storage path
-- with different immutable payload metadata is rejected.
create or replace function public.claim_ingest_batch(
  p_device_id uuid,
  p_capture_id uuid,
  p_trading_date date,
  p_captured_at timestamptz,
  p_schema_version integer,
  p_storage_path text,
  p_content_sha256 text,
  p_byte_count bigint,
  p_row_counts jsonb
)
returns public.ingest_batches
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_device public.ingest_devices;
  v_batch public.ingest_batches;
begin
  if p_device_id is null
    or p_capture_id is null
    or p_trading_date is null
    or p_captured_at is null
    or p_schema_version is null
    or p_schema_version <= 0
    or nullif(btrim(p_storage_path), '') is null
    or nullif(btrim(p_content_sha256), '') is null
    or p_byte_count is null
    or p_byte_count < 0
    or p_row_counts is null
    or not public.ingest_row_counts_are_nonnegative(p_row_counts) then
    raise exception 'batch claim metadata is invalid'
      using errcode = '22023';
  end if;

  select device.*
  into v_device
  from public.ingest_devices as device
  where device.id = p_device_id
  for update;

  if not found then
    raise exception 'ingest device is invalid'
      using errcode = 'P0002';
  end if;

  if v_device.status <> 'active' or v_device.revoked_at is not null then
    raise exception 'ingest device is revoked'
      using errcode = '22023';
  end if;

  select batch.*
  into v_batch
  from public.ingest_batches as batch
  where device_id = p_device_id
    and capture_id = p_capture_id
  for update;

  if found then
    if v_batch.trading_date is distinct from p_trading_date
      or v_batch.captured_at is distinct from p_captured_at
      or v_batch.schema_version is distinct from p_schema_version
      or v_batch.storage_path is distinct from p_storage_path
      or v_batch.content_sha256 is distinct from p_content_sha256
      or v_batch.byte_count is distinct from p_byte_count
      or v_batch.row_counts is distinct from p_row_counts then
      raise exception 'capture ID was already claimed with different metadata'
        using errcode = '22023';
    end if;

    return v_batch;
  end if;

  insert into public.ingest_batches (
    capture_id,
    device_id,
    client_id,
    trading_date,
    captured_at,
    status,
    schema_version,
    storage_path,
    content_sha256,
    byte_count,
    row_counts
  )
  values (
    p_capture_id,
    p_device_id,
    v_device.client_id,
    p_trading_date,
    p_captured_at,
    'received',
    p_schema_version,
    p_storage_path,
    p_content_sha256,
    p_byte_count,
    p_row_counts
  )
  returning * into v_batch;

  return v_batch;
end;
$function$;

revoke all on function public.claim_ingest_batch(uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb)
  from public, anon, authenticated;
grant execute on function public.claim_ingest_batch(uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb)
  to service_role;

commit;
