import { useEffect, useState } from 'react';
import { CheckSquare, Square, RotateCcw, Zap } from 'lucide-react';
import { isSupabaseConfigured } from '../lib/supabaseClient';
import { loadSupabaseDailySop, loadSupabaseDailySopTemplate, saveSupabaseDailySop } from '../domain/supabaseStore';
import { computeNewStreak, getStreak } from './dailySopUtils';

const FALLBACK_SOP_SECTIONS = [
  {
    title: 'Morning Open',
    time: '8:00–9:00 AM',
    emoji: '🌅',
    items: [
      'Log in to VPS for each client — confirm not frozen',
      'Verify all algos are active (green status in NT)',
      'Check for overnight disconnections in activity log',
      'Review open positions — no stale trades',
      'Check drawdown status on all funded accounts',
    ],
  },
  {
    title: 'Market Hours Check-In',
    time: 'Every ~1 hour',
    emoji: '📡',
    items: [
      'Verify algos still running (no silent crashes)',
      'Check P&L progress vs daily target',
      'Confirm VPS not frozen or CPU-spiked',
      'Review any new flags generated by the system',
      'Note client questions received via message — log in activity',
    ],
  },
  {
    title: 'Mid-Session Review',
    time: '12:00–1:00 PM',
    emoji: '🔍',
    items: [
      'Check if any account hit daily loss limit',
      'Review drawdown buffer on funded accounts — warning if <$1,200',
      'Verify Bullet Bot pass in progress (if applicable)',
      'Log any strategy changes or observations in activity',
      'Respond to client check-ins with status update',
    ],
  },
  {
    title: 'Market Close & Report',
    time: 'After market close',
    emoji: '📊',
    items: [
      'Import NT CSV export for each client',
      'Review and classify any Unassigned accounts',
      'Resolve or acknowledge auto-generated flags',
      'Record daily P&L, drawdown, and strategy used in report',
      'Update payout status if target profit reached',
      'Send client update (daily P&L + any notes)',
      'Close day — confirm no unresolved critical flags',
    ],
  },
  {
    title: 'End of Day Admin',
    time: 'End of session',
    emoji: '✅',
    items: [
      'Log completed tasks and update task status',
      'Note any issues or anomalies in activity log',
      'Flag accounts approaching drawdown limits for tomorrow',
      'Review tomorrow\'s price checks or scheduled events',
      'Confirm VPS still running — algos off after market hours',
    ],
  },
];

function normalizeSections(sections = []) {
  return (sections || []).map((section, sIdx) => ({
    ...section,
    key: section.key || String(sIdx),
    time: section.time || '',
    items: (section.items || []).map((item, iIdx) => {
      if (typeof item === 'string') {
        return { key: `${sIdx}-${iIdx}`, text: item };
      }
      return {
        key: item.key || item.item_key || `${sIdx}-${iIdx}`,
        text: item.text || '',
      };
    }),
  }));
}

const DEFAULT_SECTIONS = normalizeSections(FALLBACK_SOP_SECTIONS);

export default function DailySOP({ camProfileId = '' }) {
  const today = new Date().toISOString().slice(0, 10);
  const storageKey = `cam-sop-${today}`;
  const [template, setTemplate] = useState(() => ({
    id: null,
    name: 'Daily CAM Checklist',
    editableByRole: 'Manager',
    sections: DEFAULT_SECTIONS,
  }));
  const sections = template.sections?.length ? template.sections : DEFAULT_SECTIONS;
  const totalItems = sections.reduce((sum, s) => sum + s.items.length, 0);

  const [checked, setChecked] = useState(() => {
    try {
      // Prune SOP keys older than 30 days to prevent unbounded localStorage growth
      const cutoff = new Date(); cutoff.setDate(cutoff.getDate() - 30);
      const cutoffStr = cutoff.toISOString().slice(0, 10);
      Object.keys(localStorage).filter(k => k.startsWith('cam-sop-2') && k.slice(8) < cutoffStr).forEach(k => localStorage.removeItem(k));
      return JSON.parse(localStorage.getItem(storageKey) || '{}');
    } catch { return {}; }
  });
  const [justCompleted, setJustCompleted] = useState(false);
  const [streak, setStreak] = useState(() => getStreak());
  const [remoteStatus, setRemoteStatus] = useState(() => (
    isSupabaseConfigured && camProfileId ? 'loading' : 'local'
  ));

  useEffect(() => {
    if (!isSupabaseConfigured || !camProfileId) {
      return;
    }
    let cancelled = false;
    Promise.all([
      loadSupabaseDailySopTemplate(),
      loadSupabaseDailySop(camProfileId, today),
    ])
      .then(([loadedTemplate, row]) => {
        if (cancelled) return;
        if (loadedTemplate?.sections?.length) {
          setTemplate({
            ...loadedTemplate,
            sections: normalizeSections(loadedTemplate.sections),
          });
        }
        if (row) {
          setChecked(row.checked_items || {});
          setStreak({
            count: Number(row.streak_count || 0),
            lastDate: row.streak_last_date || '',
          });
        }
        setRemoteStatus('connected');
      })
      .catch((error) => {
        if (cancelled) return;
        console.error('[CRM] Failed to load Daily SOP from Supabase:', error);
        setRemoteStatus('error');
      });
    return () => { cancelled = true; };
  }, [camProfileId, today]);

  function persistDailySop(nextChecked, nextStreak, completedAt = null) {
    localStorage.setItem(storageKey, JSON.stringify(nextChecked));
    localStorage.setItem('cam-sop-streak', JSON.stringify(nextStreak));
    if (!isSupabaseConfigured || !camProfileId) return;
    saveSupabaseDailySop(camProfileId, today, nextChecked, nextStreak, completedAt, template.id).catch((error) => {
      console.error('[CRM] Failed to save Daily SOP to Supabase:', error);
      setRemoteStatus('error');
    });
  }

  function toggle(itemKey) {
    setChecked((prev) => {
      const next = { ...prev, [itemKey]: !prev[itemKey] };
      const doneCount = Object.values(next).filter(Boolean).length;
      const wasComplete = Object.values(prev).filter(Boolean).length === totalItems;
      const isNowComplete = doneCount === totalItems;
      const nextStreak = isNowComplete && !wasComplete
        ? computeNewStreak(today, streak, wasComplete, isNowComplete)
        : streak;
      setStreak(nextStreak);
      persistDailySop(next, nextStreak, isNowComplete ? new Date().toISOString() : null);
      if (isNowComplete && !wasComplete) setJustCompleted(true);
      return next;
    });
  }

  function reset() {
    setChecked({});
    setJustCompleted(false);
    localStorage.removeItem(storageKey);
    persistDailySop({}, streak, null);
  }

  const doneItems = Object.values(checked).filter(Boolean).length;
  const pct = totalItems ? Math.round((doneItems / totalItems) * 100) : 0;
  const isComplete = pct === 100;
  const currentStreak = (() => {
    if (streak.lastDate === today) return streak.count;
    const prev = new Date();
    do { prev.setDate(prev.getDate() - 1); } while ([0, 6].includes(prev.getDay()));
    return streak.lastDate === prev.toISOString().slice(0, 10) ? streak.count : 0;
  })();

  // Determine which section is currently active (first incomplete)
  const activeSectionIdx = sections.findIndex((section) =>
    section.items.some((item) => !checked[item.key])
  );

  return (
    <div className="daily-sop">
      <section className={`panel${isComplete ? ' sop-complete-panel' : ''}`}>
        <div className="panel-heading">
          <h3>{template.name || 'Daily CAM Checklist'}</h3>
          <span className="badge muted">{today}</span>
          {remoteStatus === 'connected' ? <span className="badge positive">Supabase</span> : null}
          {remoteStatus === 'loading' ? <span className="badge muted">Syncing</span> : null}
          {remoteStatus === 'error' ? <span className="badge negative">Local fallback</span> : null}
          <span className="count">{doneItems}/{totalItems}</span>
          {currentStreak > 1 && (
            <span className="sop-streak-badge"><Zap size={12} />{currentStreak} day streak</span>
          )}
          <button className="ghost-button" onClick={reset} title="Reset today's checklist">
            <RotateCcw size={14} /> Reset
          </button>
        </div>

        <div className="sop-progress-bar-wrap">
          <div
            className="sop-progress-bar"
            style={{
              width: `${pct}%`,
              background: isComplete
                ? 'var(--green)'
                : pct >= 60
                ? 'linear-gradient(90deg, var(--blue), var(--accent))'
                : 'var(--blue)',
              transition: 'width 0.3s ease, background 0.4s ease',
            }}
          />
        </div>
        <div className="sop-progress-label" style={{ color: isComplete ? 'var(--green)' : undefined }}>
          {isComplete ? '✓ All done — great work today!' : `${pct}% complete · ${totalItems - doneItems} remaining`}
        </div>

        {isComplete && justCompleted && (
          <div className="sop-celebrate">
            <span>🎉</span>
            <strong>Day complete!</strong>
            <span className="muted">All {totalItems} checklist items done.</span>
            {currentStreak > 1 && <span className="sop-streak-badge"><Zap size={12} />{currentStreak}-day streak!</span>}
          </div>
        )}

        {sections.map((section, sIdx) => {
          const sectionDone = section.items.filter((item) => checked[item.key]).length;
          const sectionComplete = sectionDone === section.items.length;
          const isActive = sIdx === activeSectionIdx;
          return (
            <div className={`sop-section${sectionComplete ? ' sop-section-done' : isActive ? ' sop-section-active' : ''}`} key={section.key || section.title}>
              <div className="sop-section-header">
                <span className="sop-section-emoji">{sectionComplete ? '✅' : section.emoji}</span>
                <span className="sop-section-title">{section.title}</span>
                <span className="sop-section-time muted">{section.time}</span>
                <span className={`sop-section-count${sectionComplete ? ' positive' : ' muted'}`}>
                  {sectionDone}/{section.items.length}
                </span>
                {sectionComplete && <span className="sop-section-badge">Done</span>}
              </div>
              <ul className="sop-list">
                {section.items.map((item, iIdx) => {
                  const done = !!checked[item.key];
                  return (
                    <li
                      key={item.key || iIdx}
                      className={`sop-item${done ? ' sop-done' : ''}`}
                      onClick={() => toggle(item.key)}
                    >
                      {done ? <CheckSquare size={15} className="positive" /> : <Square size={15} className="muted" />}
                      <span>{item.text}</span>
                    </li>
                  );
                })}
              </ul>
            </div>
          );
        })}
      </section>

      <section className="panel">
        <div className="panel-heading">
          <h3>Quick Reference</h3>
          <span className="badge muted">New CAM onboarding</span>
        </div>
        <div className="sop-ref-grid">
          <div className="sop-ref-card">
            <div className="sop-ref-title">VPS Access</div>
            <ol className="sop-ref-steps">
              <li>Find VPS credentials in client's Credentials tab</li>
              <li>RDP into VPS (Windows Remote Desktop)</li>
              <li>Open NinjaTrader — check connection status (green)</li>
              <li>Verify strategies panel — all algos active</li>
            </ol>
          </div>
          <div className="sop-ref-card">
            <div className="sop-ref-title">Add New Algo to Account</div>
            <ol className="sop-ref-steps">
              <li>Open NT Strategies panel</li>
              <li>Select account from dropdown</li>
              <li>Add strategy → choose algo (URGO / IFSP)</li>
              <li>Set quantity, confirm connection green</li>
              <li>Log in Activity tab: "Enabled [algo] on [account]"</li>
            </ol>
          </div>
          <div className="sop-ref-card">
            <div className="sop-ref-title">NT CSV Export (Daily)</div>
            <ol className="sop-ref-steps">
              <li>NT → Account Performance → Export</li>
              <li>Select date range (today only)</li>
              <li>Export: Accounts + Strategies CSV</li>
              <li>Upload both files in this app's import area</li>
            </ol>
          </div>
          <div className="sop-ref-card">
            <div className="sop-ref-title">Disconnection Protocol</div>
            <ol className="sop-ref-steps">
              <li>Check if trade is open — do NOT restart algo if position is live</li>
              <li>Wait for trade to close naturally</li>
              <li>Only then reconnect and restart strategy</li>
              <li>Log disconnection in Activity: time, account, resolution</li>
            </ol>
          </div>
        </div>
      </section>
    </div>
  );
}
